import { Metadata } from "next"

export const metadata: Metadata = {
  title: 'Contact page',
  description: 'Generated by create next app',
}

const ContactPage = () => {
  return (
    <div className="text">ContactPage</div>
  )
}

export default ContactPage